package project.teacher.teachermanage.pojo;

import java.util.Date;

public class EduTeacherBasicInfo {
	
	private Integer teacherCountry;
	
	

	private Integer status;
	
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer teacherId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_old_name
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherOldName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_name_spelling
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherNameSpelling;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_born_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherBornDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_political_status
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherPoliticalStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_native_place
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherNativePlace;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_nation
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherNation;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_phone_num
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherPhoneNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_call_num
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherCallNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_qq
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherQq;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_email
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherEmail;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_family_local
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherFamilyLocal;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_marital_status
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherMaritalStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_health_condition
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherHealthCondition;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.version
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_create_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherCreateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_update_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String teacherUpdateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_create_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Date teacherCreateDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_basic_info.teacher_update_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Date teacherUpdateDate;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.id
	 * @return  the value of edu_teacher_basic_info.id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.id
	 * @param id  the value for edu_teacher_basic_info.id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_id
	 * @return  the value of edu_teacher_basic_info.teacher_id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_id
	 * @param teacherId  the value for edu_teacher_basic_info.teacher_id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_old_name
	 * @return  the value of edu_teacher_basic_info.teacher_old_name
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherOldName() {
		return teacherOldName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_old_name
	 * @param teacherOldName  the value for edu_teacher_basic_info.teacher_old_name
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherOldName(String teacherOldName) {
		this.teacherOldName = teacherOldName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_name_spelling
	 * @return  the value of edu_teacher_basic_info.teacher_name_spelling
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherNameSpelling() {
		return teacherNameSpelling;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_name_spelling
	 * @param teacherNameSpelling  the value for edu_teacher_basic_info.teacher_name_spelling
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherNameSpelling(String teacherNameSpelling) {
		this.teacherNameSpelling = teacherNameSpelling;
	}


	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_born_date
	 * @param teacherBornDate  the value for edu_teacher_basic_info.teacher_born_date
//	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
//	 */
//	public void setTeacherBornDate(String teacherBornDateStr) {
//		Date tempDate = DateConvertUtils.parse(teacherBornDateStr, "yyyy-MM-dd");
//		System.out.println(tempDate);
//		this.teacherBornDate = tempDate;
//	}



	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_political_status
	 * @return  the value of edu_teacher_basic_info.teacher_political_status
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherPoliticalStatus() {
		return teacherPoliticalStatus;
	}

	public String getTeacherBornDate() {
		return teacherBornDate;
	}

	public void setTeacherBornDate(String teacherBornDate) {
		this.teacherBornDate = teacherBornDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_political_status
	 * @param teacherPoliticalStatus  the value for edu_teacher_basic_info.teacher_political_status
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherPoliticalStatus(String teacherPoliticalStatus) {
		this.teacherPoliticalStatus = teacherPoliticalStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_native_place
	 * @return  the value of edu_teacher_basic_info.teacher_native_place
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherNativePlace() {
		return teacherNativePlace;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_native_place
	 * @param teacherNativePlace  the value for edu_teacher_basic_info.teacher_native_place
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherNativePlace(String teacherNativePlace) {
		this.teacherNativePlace = teacherNativePlace;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_nation
	 * @return  the value of edu_teacher_basic_info.teacher_nation
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherNation() {
		return teacherNation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_nation
	 * @param teacherNation  the value for edu_teacher_basic_info.teacher_nation
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherNation(String teacherNation) {
		this.teacherNation = teacherNation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_phone_num
	 * @return  the value of edu_teacher_basic_info.teacher_phone_num
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherPhoneNum() {
		return teacherPhoneNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_phone_num
	 * @param teacherPhoneNum  the value for edu_teacher_basic_info.teacher_phone_num
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherPhoneNum(String teacherPhoneNum) {
		this.teacherPhoneNum = teacherPhoneNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_call_num
	 * @return  the value of edu_teacher_basic_info.teacher_call_num
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherCallNum() {
		return teacherCallNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_call_num
	 * @param teacherCallNum  the value for edu_teacher_basic_info.teacher_call_num
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherCallNum(String teacherCallNum) {
		this.teacherCallNum = teacherCallNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_qq
	 * @return  the value of edu_teacher_basic_info.teacher_qq
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherQq() {
		return teacherQq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_qq
	 * @param teacherQq  the value for edu_teacher_basic_info.teacher_qq
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherQq(String teacherQq) {
		this.teacherQq = teacherQq;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_email
	 * @return  the value of edu_teacher_basic_info.teacher_email
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherEmail() {
		return teacherEmail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_email
	 * @param teacherEmail  the value for edu_teacher_basic_info.teacher_email
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherEmail(String teacherEmail) {
		this.teacherEmail = teacherEmail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_family_local
	 * @return  the value of edu_teacher_basic_info.teacher_family_local
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherFamilyLocal() {
		return teacherFamilyLocal;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_family_local
	 * @param teacherFamilyLocal  the value for edu_teacher_basic_info.teacher_family_local
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherFamilyLocal(String teacherFamilyLocal) {
		this.teacherFamilyLocal = teacherFamilyLocal;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_marital_status
	 * @return  the value of edu_teacher_basic_info.teacher_marital_status
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherMaritalStatus() {
		return teacherMaritalStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_marital_status
	 * @param teacherMaritalStatus  the value for edu_teacher_basic_info.teacher_marital_status
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherMaritalStatus(String teacherMaritalStatus) {
		this.teacherMaritalStatus = teacherMaritalStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_health_condition
	 * @return  the value of edu_teacher_basic_info.teacher_health_condition
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherHealthCondition() {
		return teacherHealthCondition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_health_condition
	 * @param teacherHealthCondition  the value for edu_teacher_basic_info.teacher_health_condition
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherHealthCondition(String teacherHealthCondition) {
		this.teacherHealthCondition = teacherHealthCondition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.version
	 * @return  the value of edu_teacher_basic_info.version
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.version
	 * @param version  the value for edu_teacher_basic_info.version
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_create_by
	 * @return  the value of edu_teacher_basic_info.teacher_create_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherCreateBy() {
		return teacherCreateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_create_by
	 * @param teacherCreateBy  the value for edu_teacher_basic_info.teacher_create_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherCreateBy(String teacherCreateBy) {
		this.teacherCreateBy = teacherCreateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_update_by
	 * @return  the value of edu_teacher_basic_info.teacher_update_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getTeacherUpdateBy() {
		return teacherUpdateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_update_by
	 * @param teacherUpdateBy  the value for edu_teacher_basic_info.teacher_update_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherUpdateBy(String teacherUpdateBy) {
		this.teacherUpdateBy = teacherUpdateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_create_date
	 * @return  the value of edu_teacher_basic_info.teacher_create_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Date getTeacherCreateDate() {
		return teacherCreateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_create_date
	 * @param teacherCreateDate  the value for edu_teacher_basic_info.teacher_create_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherCreateDate(Date teacherCreateDate) {
		this.teacherCreateDate = teacherCreateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_basic_info.teacher_update_date
	 * @return  the value of edu_teacher_basic_info.teacher_update_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Date getTeacherUpdateDate() {
		return teacherUpdateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_basic_info.teacher_update_date
	 * @param teacherUpdateDate  the value for edu_teacher_basic_info.teacher_update_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherUpdateDate(Date teacherUpdateDate) {
		this.teacherUpdateDate = teacherUpdateDate;
	}

	public Integer getTeacherCountry() {
		return teacherCountry;
	}

	public void setTeacherCountry(Integer teacherCountry) {
		this.teacherCountry = teacherCountry;
	}

	//入党时间
	private String partyTime;

	public String getPartyTime() {
		return partyTime;
	}

	public void setPartyTime(String partyTime) {
		this.partyTime = partyTime;
	}
	
	 
}