package project.furtheredu.edumanage.pojo;

import java.util.Date;

public class EduProjectComment {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer id;
    private Integer districtExamine;
    public String getDistrictMemo() {
		return districtMemo;
	}

	public void setDistrictMemo(String districtMemo) {
		this.districtMemo = districtMemo;
	}

	public String getCityMemo() {
		return cityMemo;
	}

	public void setCityMemo(String cityMemo) {
		this.cityMemo = cityMemo;
	}

	public String getProvinceMemo() {
		return provinceMemo;
	}

	public void setProvinceMemo(String provinceMemo) {
		this.provinceMemo = provinceMemo;
	}

	private String districtMemo;
    private String cityMemo;
    private String provinceMemo;
    public Integer getDistrictExamine() {
		return districtExamine;
	}

	public void setDistrictExamine(Integer districtExamine) {
		this.districtExamine = districtExamine;
	}

	public Integer getCityExamine() {
		return cityExamine;
	}

	public void setCityExamine(Integer cityExamine) {
		this.cityExamine = cityExamine;
	}

	public Integer getProvinceExamine() {
		return provinceExamine;
	}

	public void setProvinceExamine(Integer provinceExamine) {
		this.provinceExamine = provinceExamine;
	}

	public Integer getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Integer getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	private Integer cityExamine;
    private Integer provinceExamine;
    private Integer schoolId;
    private Integer cityId;
    private Integer districtId;
    private Integer provinceId;
    
    private String opinion;
    
    public String getOpinion() {
		return opinion;
	}

	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.project_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.project_score
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Float projectScore;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.teacher_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.organization_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer organizationId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.status
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.teacher_score
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Float teacherScore;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.teacher_train_status_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer teacherTrainStatusId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.teacher_train_status_name
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private String teacherTrainStatusName;
    
    
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.create_by
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.create_date
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.update_by
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.update_date
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.teacher_score_audit_status_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer teacherScoreAuditStatusId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.teacher_score_audit_status_name
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private String teacherScoreAuditStatusName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_comment.audit_memo
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private String auditMemo;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.id
     *
     * @return the value of edu_project_comment.id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    private Integer examine;
	
	

	public Integer getExamine() {
		return examine;
	}

	public void setExamine(Integer examine) {
		this.examine = examine;
	}
	
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.id
     *
     * @param id the value for edu_project_comment.id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.project_id
     *
     * @return the value of edu_project_comment.project_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.project_id
     *
     * @param projectId the value for edu_project_comment.project_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.project_score
     *
     * @return the value of edu_project_comment.project_score
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Float getProjectScore() {
        return projectScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.project_score
     *
     * @param projectScore the value for edu_project_comment.project_score
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setProjectScore(Float projectScore) {
        this.projectScore = projectScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.teacher_id
     *
     * @return the value of edu_project_comment.teacher_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.teacher_id
     *
     * @param teacherId the value for edu_project_comment.teacher_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.organization_id
     *
     * @return the value of edu_project_comment.organization_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.organization_id
     *
     * @param organizationId the value for edu_project_comment.organization_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.status
     *
     * @return the value of edu_project_comment.status
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.status
     *
     * @param status the value for edu_project_comment.status
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.teacher_score
     *
     * @return the value of edu_project_comment.teacher_score
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Float getTeacherScore() {
        return teacherScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.teacher_score
     *
     * @param teacherScore the value for edu_project_comment.teacher_score
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setTeacherScore(Float teacherScore) {
        this.teacherScore = teacherScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.teacher_train_status_id
     *
     * @return the value of edu_project_comment.teacher_train_status_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Integer getTeacherTrainStatusId() {
        return teacherTrainStatusId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.teacher_train_status_id
     *
     * @param teacherTrainStatusId the value for edu_project_comment.teacher_train_status_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setTeacherTrainStatusId(Integer teacherTrainStatusId) {
        this.teacherTrainStatusId = teacherTrainStatusId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.teacher_train_status_name
     *
     * @return the value of edu_project_comment.teacher_train_status_name
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public String getTeacherTrainStatusName() {
        return teacherTrainStatusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.teacher_train_status_name
     *
     * @param teacherTrainStatusName the value for edu_project_comment.teacher_train_status_name
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setTeacherTrainStatusName(String teacherTrainStatusName) {
        this.teacherTrainStatusName = teacherTrainStatusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.create_by
     *
     * @return the value of edu_project_comment.create_by
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.create_by
     *
     * @param createBy the value for edu_project_comment.create_by
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.create_date
     *
     * @return the value of edu_project_comment.create_date
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.create_date
     *
     * @param createDate the value for edu_project_comment.create_date
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.update_by
     *
     * @return the value of edu_project_comment.update_by
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.update_by
     *
     * @param updateBy the value for edu_project_comment.update_by
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.update_date
     *
     * @return the value of edu_project_comment.update_date
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.update_date
     *
     * @param updateDate the value for edu_project_comment.update_date
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.teacher_score_audit_status_id
     *
     * @return the value of edu_project_comment.teacher_score_audit_status_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public Integer getTeacherScoreAuditStatusId() {
        return teacherScoreAuditStatusId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.teacher_score_audit_status_id
     *
     * @param teacherScoreAuditStatusId the value for edu_project_comment.teacher_score_audit_status_id
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setTeacherScoreAuditStatusId(Integer teacherScoreAuditStatusId) {
        this.teacherScoreAuditStatusId = teacherScoreAuditStatusId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.teacher_score_audit_status_name
     *
     * @return the value of edu_project_comment.teacher_score_audit_status_name
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public String getTeacherScoreAuditStatusName() {
        return teacherScoreAuditStatusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.teacher_score_audit_status_name
     *
     * @param teacherScoreAuditStatusName the value for edu_project_comment.teacher_score_audit_status_name
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setTeacherScoreAuditStatusName(String teacherScoreAuditStatusName) {
        this.teacherScoreAuditStatusName = teacherScoreAuditStatusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_comment.audit_memo
     *
     * @return the value of edu_project_comment.audit_memo
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public String getAuditMemo() {
        return auditMemo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_comment.audit_memo
     *
     * @param auditMemo the value for edu_project_comment.audit_memo
     *
     * @abatorgenerated Sun Mar 30 15:32:14 CST 2014
     */
    public void setAuditMemo(String auditMemo) {
        this.auditMemo = auditMemo;
    }

	 
}