package project.person.pojo;

import java.util.Date;

public class EduUser {
	
	private String userImageUrl;
	private Integer userProvinceId;
	private String userProvinceName;
	private Integer userCityId;
	private String userCityName;
	private Integer userDistrictId;
	private String userDistrictName;
	private String userAddress;
	private String userStatus;
	private String roleName;
	//角色类型名称
	private String roleTypeName;
	private Integer roleTypeId;
	private String sex;
	private String statusName;
	private String oldLoginAccount;
	private String auditName;
	private Date auditDate;
	private Integer subjectId;
	private String subjectName;
	private Integer organizationId;
	
	private String teacherScore; //教师成线;非培训类项目教师登记学分
	private Integer projectId;
	private String auditScore; //审核学分 
	private Integer auditStatus;//学分审核状态
	
	private String teacherClassPeriod;//教师所获得学时
	
	private Integer isPassword;//是否修改过密码
	private Integer uId;
	
	private Integer examine;
	
	private String trainStatusName; //培训状态
	
	public Integer getExamine() {
		return examine;
	}

	public void setExamine(Integer examine) {
		this.examine = examine;
	}

	public Integer getuId() {
		return uId;
	}

	public void setuId(Integer uId) {
		this.uId = uId;
	}

	public String getTeacherScore() {
		return teacherScore;
	}

	public void setTeacherScore(String teacherScore) {
		this.teacherScore = teacherScore;
	}

	public String getAuditScore() {
		return auditScore;
	}

	public void setAuditScore(String auditScore) {
		this.auditScore = auditScore;
	}

	public String getTeacherClassPeriod() {
		return teacherClassPeriod;
	}

	public void setTeacherClassPeriod(String teacherClassPeriod) {
		this.teacherClassPeriod = teacherClassPeriod;
	}

	public Integer getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	public Integer getSubjectId() {
		return subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public String getAuditName() {
		return auditName;
	}

	public void setAuditName(String auditName) {
		this.auditName = auditName;
	}

	public Date getAuditDate() {
		return auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	private String memo;
	
    public String getOldLoginAccount() {
		return oldLoginAccount;
	}

	public void setOldLoginAccount(String oldLoginAccount) {
		this.oldLoginAccount = oldLoginAccount;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getUserStatus() {
		return userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserImageUrl() {
		return userImageUrl;
	}

	public Integer getUserProvinceId() {
		return userProvinceId;
	}

	public void setUserProvinceId(Integer userProvinceId) {
		this.userProvinceId = userProvinceId;
	}

	public Integer getUserCityId() {
		return userCityId;
	}

	public void setUserCityId(Integer userCityId) {
		this.userCityId = userCityId;
	}

	public Integer getUserDistrictId() {
		return userDistrictId;
	}

	public void setUserDistrictId(Integer userDistrictId) {
		this.userDistrictId = userDistrictId;
	}

	public void setUserImageUrl(String userImageUrl) {
		this.userImageUrl = userImageUrl;
	}

	public String getUserProvinceName() {
		return userProvinceName;
	}

	public void setUserProvinceName(String userProvinceName) {
		this.userProvinceName = userProvinceName;
	}


	public String getUserCityName() {
		return userCityName;
	}

	public void setUserCityName(String userCityName) {
		this.userCityName = userCityName;
	}

	public String getUserDistrictName() {
		return userDistrictName;
	}

	public void setUserDistrictName(String userDistrictName) {
		this.userDistrictName = userDistrictName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.login_account
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String loginAccount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.real_name
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String realName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.role_id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.id_number
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String idNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.mail
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String mail;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.mobile
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.paswd_question_type
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer paswdQuestionType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.paswd_answer
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String paswdAnswer;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.password
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.create_by
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.update_by
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.create_date
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.update_date
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.status
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.version
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer version;
    
    
    //schoolName
    private String schoolName;

    public String getSchoolName() {
		return schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.teacher_no
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private String teacherNo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.school_id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer schoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_user.gender
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    private Integer gender;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.id
     *
     * @return the value of edu_user.id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.id
     *
     * @param id the value for edu_user.id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.login_account
     *
     * @return the value of edu_user.login_account
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.login_account
     *
     * @param loginAccount the value for edu_user.login_account
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.real_name
     *
     * @return the value of edu_user.real_name
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.real_name
     *
     * @param realName the value for edu_user.real_name
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.role_id
     *
     * @return the value of edu_user.role_id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.role_id
     *
     * @param roleId the value for edu_user.role_id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.id_number
     *
     * @return the value of edu_user.id_number
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.id_number
     *
     * @param idNumber the value for edu_user.id_number
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.mail
     *
     * @return the value of edu_user.mail
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.mail
     *
     * @param mail the value for edu_user.mail
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.mobile
     *
     * @return the value of edu_user.mobile
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.mobile
     *
     * @param mobile the value for edu_user.mobile
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.paswd_question_type
     *
     * @return the value of edu_user.paswd_question_type
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getPaswdQuestionType() {
        return paswdQuestionType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.paswd_question_type
     *
     * @param paswdQuestionType the value for edu_user.paswd_question_type
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setPaswdQuestionType(Integer paswdQuestionType) {
        this.paswdQuestionType = paswdQuestionType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.paswd_answer
     *
     * @return the value of edu_user.paswd_answer
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getPaswdAnswer() {
        return paswdAnswer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.paswd_answer
     *
     * @param paswdAnswer the value for edu_user.paswd_answer
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setPaswdAnswer(String paswdAnswer) {
        this.paswdAnswer = paswdAnswer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.password
     *
     * @return the value of edu_user.password
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.password
     *
     * @param password the value for edu_user.password
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.create_by
     *
     * @return the value of edu_user.create_by
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.create_by
     *
     * @param createBy the value for edu_user.create_by
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.update_by
     *
     * @return the value of edu_user.update_by
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.update_by
     *
     * @param updateBy the value for edu_user.update_by
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.create_date
     *
     * @return the value of edu_user.create_date
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.create_date
     *
     * @param createDate the value for edu_user.create_date
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.update_date
     *
     * @return the value of edu_user.update_date
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.update_date
     *
     * @param updateDate the value for edu_user.update_date
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.status
     *
     * @return the value of edu_user.status
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.status
     *
     * @param status the value for edu_user.status
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.version
     *
     * @return the value of edu_user.version
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.version
     *
     * @param version the value for edu_user.version
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.teacher_no
     *
     * @return the value of edu_user.teacher_no
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public String getTeacherNo() {
        return teacherNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.teacher_no
     *
     * @param teacherNo the value for edu_user.teacher_no
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setTeacherNo(String teacherNo) {
        this.teacherNo = teacherNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.school_id
     *
     * @return the value of edu_user.school_id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.school_id
     *
     * @param schoolId the value for edu_user.school_id
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.gender
     *
     * @return the value of edu_user.gender
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.gender
     *
     * @param gender the value for edu_user.gender
     *
     * @abatorgenerated Thu Mar 27 21:28:59 CST 2014
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

 

	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	 
	public Integer getAuditStatus() {
		return auditStatus;
	}

	public void setAuditStatus(Integer auditStatus) {
		this.auditStatus = auditStatus;
	}

	public Integer getIsPassword() {
		return isPassword;
	}

	public void setIsPassword(Integer isPassword) {
		this.isPassword = isPassword;
	}

	public String getRoleTypeName() {
		return roleTypeName;
	}

	public void setRoleTypeName(String roleTypeName) {
		this.roleTypeName = roleTypeName;
	}

	public Integer getRoleTypeId() {
		return roleTypeId;
	}

	public void setRoleTypeId(Integer roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public String getTrainStatusName() {
		return trainStatusName;
	}

	public void setTrainStatusName(String trainStatusName) {
		this.trainStatusName = trainStatusName;
	}
	
	
	
}