package project.system.pojo;

public class SysDictionary {
	
	private Integer status;
    public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_sys_dictionary.id
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    private Integer id;
    
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_sys_dictionary.dictionary_id
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    private Integer dictionaryId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_sys_dictionary.dictionary_type
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    private String dictionaryType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_sys_dictionary.dictionary_type_name
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    private String dictionaryTypeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_sys_dictionary.dictionary_name
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    private String dictionaryName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_sys_dictionary.dictionary_code
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    private String dictionaryCode;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_sys_dictionary.id
     *
     * @return the value of edu_sys_dictionary.id
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_sys_dictionary.id
     *
     * @param id the value for edu_sys_dictionary.id
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_sys_dictionary.dictionary_id
     *
     * @return the value of edu_sys_dictionary.dictionary_id
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public Integer getDictionaryId() {
        return dictionaryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_sys_dictionary.dictionary_id
     *
     * @param dictionaryId the value for edu_sys_dictionary.dictionary_id
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public void setDictionaryId(Integer dictionaryId) {
        this.dictionaryId = dictionaryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_sys_dictionary.dictionary_type
     *
     * @return the value of edu_sys_dictionary.dictionary_type
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public String getDictionaryType() {
        return dictionaryType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_sys_dictionary.dictionary_type
     *
     * @param dictionaryType the value for edu_sys_dictionary.dictionary_type
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public void setDictionaryType(String dictionaryType) {
        this.dictionaryType = dictionaryType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_sys_dictionary.dictionary_type_name
     *
     * @return the value of edu_sys_dictionary.dictionary_type_name
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public String getDictionaryTypeName() {
        return dictionaryTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_sys_dictionary.dictionary_type_name
     *
     * @param dictionaryTypeName the value for edu_sys_dictionary.dictionary_type_name
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public void setDictionaryTypeName(String dictionaryTypeName) {
        this.dictionaryTypeName = dictionaryTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_sys_dictionary.dictionary_name
     *
     * @return the value of edu_sys_dictionary.dictionary_name
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public String getDictionaryName() {
        return dictionaryName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_sys_dictionary.dictionary_name
     *
     * @param dictionaryName the value for edu_sys_dictionary.dictionary_name
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public void setDictionaryName(String dictionaryName) {
        this.dictionaryName = dictionaryName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_sys_dictionary.dictionary_code
     *
     * @return the value of edu_sys_dictionary.dictionary_code
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public String getDictionaryCode() {
        return dictionaryCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_sys_dictionary.dictionary_code
     *
     * @param dictionaryCode the value for edu_sys_dictionary.dictionary_code
     *
     * @abatorgenerated Thu Mar 27 17:07:44 CST 2014
     */
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode;
    }
}