package project.system.pojo;

import java.util.Date;

public class EduSchool {
	
	private Integer areaTypeId;
	private String areaTypeName;
	private String schoolCode;
	private String oldSchoolCode;
	private Integer establishTypeId;
	private String establishTypeName;
	
	public String getOldSchoolCode() {
		return oldSchoolCode;
	}

	public void setOldSchoolCode(String oldSchoolCode) {
		this.oldSchoolCode = oldSchoolCode;
	}

	public String getSchoolCode() {
		return schoolCode;
	}

	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

	public Integer getAreaTypeId() {
		return areaTypeId;
	}

	public void setAreaTypeId(Integer areaTypeId) {
		this.areaTypeId = areaTypeId;
	}

	public String getAreaTypeName() {
		return areaTypeName;
	}

	public void setAreaTypeName(String areaTypeName) {
		this.areaTypeName = areaTypeName;
	}

	private Integer schoolNatureId;
	private String schoolNatureName;
	
	public Integer getSchoolNatureId() {
		return schoolNatureId;
	}

	public void setSchoolNatureId(Integer schoolNatureId) {
		this.schoolNatureId = schoolNatureId;
	}

	public String getSchoolNatureName() {
		return schoolNatureName;
	}

	public void setSchoolNatureName(String schoolNatureName) {
		this.schoolNatureName = schoolNatureName;
	}

	private Integer status;
	 
	 
    public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Integer schoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_type_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Integer schoolTypeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_type_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolTypeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_province_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Integer schoolProvinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_province_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolProvinceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_city_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Integer schoolCityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_city_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolCityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_district_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Integer schoolDistrictId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_district_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolDistrictName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_contacts
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolContacts;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_contacts_type
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolContactsType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_contacts_address
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolContactsAddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.school_memo
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String schoolMemo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.create_by
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.create_date
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.update_by
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_school.update_date
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_id
     *
     * @return the value of edu_school.school_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_id
     *
     * @param schoolId the value for edu_school.school_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_name
     *
     * @return the value of edu_school.school_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_name
     *
     * @param schoolName the value for edu_school.school_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_type_id
     *
     * @return the value of edu_school.school_type_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Integer getSchoolTypeId() {
        return schoolTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_type_id
     *
     * @param schoolTypeId the value for edu_school.school_type_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolTypeId(Integer schoolTypeId) {
        this.schoolTypeId = schoolTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_type_name
     *
     * @return the value of edu_school.school_type_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolTypeName() {
        return schoolTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_type_name
     *
     * @param schoolTypeName the value for edu_school.school_type_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolTypeName(String schoolTypeName) {
        this.schoolTypeName = schoolTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_province_id
     *
     * @return the value of edu_school.school_province_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Integer getSchoolProvinceId() {
        return schoolProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_province_id
     *
     * @param schoolProvinceId the value for edu_school.school_province_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolProvinceId(Integer schoolProvinceId) {
        this.schoolProvinceId = schoolProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_province_name
     *
     * @return the value of edu_school.school_province_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolProvinceName() {
        return schoolProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_province_name
     *
     * @param schoolProvinceName the value for edu_school.school_province_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolProvinceName(String schoolProvinceName) {
        this.schoolProvinceName = schoolProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_city_id
     *
     * @return the value of edu_school.school_city_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Integer getSchoolCityId() {
        return schoolCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_city_id
     *
     * @param schoolCityId the value for edu_school.school_city_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolCityId(Integer schoolCityId) {
        this.schoolCityId = schoolCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_city_name
     *
     * @return the value of edu_school.school_city_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolCityName() {
        return schoolCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_city_name
     *
     * @param schoolCityName the value for edu_school.school_city_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolCityName(String schoolCityName) {
        this.schoolCityName = schoolCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_district_id
     *
     * @return the value of edu_school.school_district_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Integer getSchoolDistrictId() {
        return schoolDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_district_id
     *
     * @param schoolDistrictId the value for edu_school.school_district_id
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolDistrictId(Integer schoolDistrictId) {
        this.schoolDistrictId = schoolDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_district_name
     *
     * @return the value of edu_school.school_district_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolDistrictName() {
        return schoolDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_district_name
     *
     * @param schoolDistrictName the value for edu_school.school_district_name
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolDistrictName(String schoolDistrictName) {
        this.schoolDistrictName = schoolDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_contacts
     *
     * @return the value of edu_school.school_contacts
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolContacts() {
        return schoolContacts;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_contacts
     *
     * @param schoolContacts the value for edu_school.school_contacts
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolContacts(String schoolContacts) {
        this.schoolContacts = schoolContacts;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_contacts_type
     *
     * @return the value of edu_school.school_contacts_type
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolContactsType() {
        return schoolContactsType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_contacts_type
     *
     * @param schoolContactsType the value for edu_school.school_contacts_type
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolContactsType(String schoolContactsType) {
        this.schoolContactsType = schoolContactsType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_contacts_address
     *
     * @return the value of edu_school.school_contacts_address
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolContactsAddress() {
        return schoolContactsAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_contacts_address
     *
     * @param schoolContactsAddress the value for edu_school.school_contacts_address
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolContactsAddress(String schoolContactsAddress) {
        this.schoolContactsAddress = schoolContactsAddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.school_memo
     *
     * @return the value of edu_school.school_memo
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getSchoolMemo() {
        return schoolMemo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.school_memo
     *
     * @param schoolMemo the value for edu_school.school_memo
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setSchoolMemo(String schoolMemo) {
        this.schoolMemo = schoolMemo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.create_by
     *
     * @return the value of edu_school.create_by
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.create_by
     *
     * @param createBy the value for edu_school.create_by
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.create_date
     *
     * @return the value of edu_school.create_date
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.create_date
     *
     * @param createDate the value for edu_school.create_date
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.update_by
     *
     * @return the value of edu_school.update_by
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.update_by
     *
     * @param updateBy the value for edu_school.update_by
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_school.update_date
     *
     * @return the value of edu_school.update_date
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_school.update_date
     *
     * @param updateDate the value for edu_school.update_date
     *
     * @abatorgenerated Tue Apr 01 16:32:19 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    private String provinceId;
    private String cityId;
    private String districtId;
    private String userSchoolId;
    private Integer roleId;

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public String getCityId() {
		return cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getDistrictId() {
		return districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

	public String getUserSchoolId() {
		return userSchoolId;
	}

	public void setUserSchoolId(String userSchoolId) {
		this.userSchoolId = userSchoolId;
	}

	public Integer getEstablishTypeId() {
		return establishTypeId;
	}

	public void setEstablishTypeId(Integer establishTypeId) {
		this.establishTypeId = establishTypeId;
	}

	public String getEstablishTypeName() {
		return establishTypeName;
	}

	public void setEstablishTypeName(String establishTypeName) {
		this.establishTypeName = establishTypeName;
	}
    
	
	
    
}