package project.system.pojo;

import java.util.Date;

public class FjimportHistory {
	private String historyType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.id
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private Integer id;
	
	private String address;

	public String getHistoryType() {
		return historyType;
	}

	public void setHistoryType(String historyType) {
		this.historyType = historyType;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.create_date
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private Date createDate;
	
	private String createDateStr;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.create_by
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private String createBy;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.import_success_count
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private Integer importSuccessCount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.imort_fail_count
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private Integer imortFailCount;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.import_file_name
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private String importFileName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.import_fail_url
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private String importFailUrl;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.import_serial
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private Integer importSerial;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.option_real_name
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private String optionRealName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_teacher_import_history.option_year
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	private Integer optionYear;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.id
	 * 
	 * @return the value of edu_teacher_import_history.id
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.id
	 * 
	 * @param id
	 *            the value for edu_teacher_import_history.id
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.create_date
	 * 
	 * @return the value of edu_teacher_import_history.create_date
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.create_date
	 * 
	 * @param createDate
	 *            the value for edu_teacher_import_history.create_date
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.create_by
	 * 
	 * @return the value of edu_teacher_import_history.create_by
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.create_by
	 * 
	 * @param createBy
	 *            the value for edu_teacher_import_history.create_by
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column
	 * edu_teacher_import_history.import_success_count
	 * 
	 * @return the value of edu_teacher_import_history.import_success_count
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public Integer getImportSuccessCount() {
		return importSuccessCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column
	 * edu_teacher_import_history.import_success_count
	 * 
	 * @param importSuccessCount
	 *            the value for edu_teacher_import_history.import_success_count
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setImportSuccessCount(Integer importSuccessCount) {
		this.importSuccessCount = importSuccessCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.imort_fail_count
	 * 
	 * @return the value of edu_teacher_import_history.imort_fail_count
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public Integer getImortFailCount() {
		return imortFailCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.imort_fail_count
	 * 
	 * @param imortFailCount
	 *            the value for edu_teacher_import_history.imort_fail_count
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setImortFailCount(Integer imortFailCount) {
		this.imortFailCount = imortFailCount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.import_file_name
	 * 
	 * @return the value of edu_teacher_import_history.import_file_name
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public String getImportFileName() {
		return importFileName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.import_file_name
	 * 
	 * @param importFileName
	 *            the value for edu_teacher_import_history.import_file_name
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setImportFileName(String importFileName) {
		this.importFileName = importFileName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.import_fail_url
	 * 
	 * @return the value of edu_teacher_import_history.import_fail_url
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public String getImportFailUrl() {
		return importFailUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.import_fail_url
	 * 
	 * @param importFailUrl
	 *            the value for edu_teacher_import_history.import_fail_url
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setImportFailUrl(String importFailUrl) {
		this.importFailUrl = importFailUrl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.import_serial
	 * 
	 * @return the value of edu_teacher_import_history.import_serial
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public Integer getImportSerial() {
		return importSerial;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.import_serial
	 * 
	 * @param importSerial
	 *            the value for edu_teacher_import_history.import_serial
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setImportSerial(Integer importSerial) {
		this.importSerial = importSerial;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.option_real_name
	 * 
	 * @return the value of edu_teacher_import_history.option_real_name
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public String getOptionRealName() {
		return optionRealName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.option_real_name
	 * 
	 * @param optionRealName
	 *            the value for edu_teacher_import_history.option_real_name
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setOptionRealName(String optionRealName) {
		this.optionRealName = optionRealName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_teacher_import_history.option_year
	 * 
	 * @return the value of edu_teacher_import_history.option_year
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public Integer getOptionYear() {
		return optionYear;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_teacher_import_history.option_year
	 * 
	 * @param optionYear
	 *            the value for edu_teacher_import_history.option_year
	 * 
	 * @abatorgenerated Tue Apr 22 10:22:31 CST 2014
	 */
	public void setOptionYear(Integer optionYear) {
		this.optionYear = optionYear;
	}

	public String getCreateDateStr() {
		return createDateStr;
	}

	public void setCreateDateStr(String createDateStr) {
		this.createDateStr = createDateStr;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	
	
}
