package project.message.pojo;

import java.util.Date;

public class EduMessage {
	
    private Integer id;
    private String receiveUserName;
    private String fileUrl;		//附件路径
    private String auditMemo;
    private String projectName;
    private Integer messageType; //消息类型  1=省级通知  2=市级通知  3=区级通知  4=校级通知
    private String fileName; 	//附件名称
    private Integer messageUserId; //消息用户主键
    
    //非持久化字段，用来对信息进行分地区显示
  	private String from;
  	
    private Integer num;  	 //来自各省/市/区/校未读数量
    
    public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}
	
    public String getAuditMemo() {
		return auditMemo;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public void setAuditMemo(String auditMemo) {
		this.auditMemo = auditMemo;
	}

	public String getReceiveUserName() {
		return receiveUserName;
	}

	public void setReceiveUserName(String receiveUserName) {
		this.receiveUserName = receiveUserName;
	}

	public String getSendUserName() {
		return sendUserName;
	}

	public void setSendUserName(String sendUserName) {
		this.sendUserName = sendUserName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.status
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.create_by
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.create_date
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.update_by
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.update_date
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.receive_user_id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private Integer receiveUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.send_user_id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private Integer sendUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.title
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.send_time
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private Date sendTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.sendUserName
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private String sendUserName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_message.content
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    private String content;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.id
     *
     * @return the value of edu_message.id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.id
     *
     * @param id the value for edu_message.id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.status
     *
     * @return the value of edu_message.status
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.status
     *
     * @param status the value for edu_message.status
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.create_by
     *
     * @return the value of edu_message.create_by
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.create_by
     *
     * @param createBy the value for edu_message.create_by
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.create_date
     *
     * @return the value of edu_message.create_date
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.create_date
     *
     * @param createDate the value for edu_message.create_date
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.update_by
     *
     * @return the value of edu_message.update_by
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.update_by
     *
     * @param updateBy the value for edu_message.update_by
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.update_date
     *
     * @return the value of edu_message.update_date
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.update_date
     *
     * @param updateDate the value for edu_message.update_date
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.receive_user_id
     *
     * @return the value of edu_message.receive_user_id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Integer getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.receive_user_id
     *
     * @param receiveUserId the value for edu_message.receive_user_id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setReceiveUserId(Integer receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.send_user_id
     *
     * @return the value of edu_message.send_user_id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.send_user_id
     *
     * @param sendUserId the value for edu_message.send_user_id
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.title
     *
     * @return the value of edu_message.title
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.title
     *
     * @param title the value for edu_message.title
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.send_time
     *
     * @return the value of edu_message.send_time
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.send_time
     *
     * @param sendTime the value for edu_message.send_time
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_message.content
     *
     * @return the value of edu_message.content
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_message.content
     *
     * @param content the value for edu_message.content
     *
     * @abatorgenerated Sat Apr 19 20:23:08 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
    public Integer getMessageType() {
		return messageType;
	}

	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getFileUrl() {
		return fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	public Integer getMessageUserId() {
		return messageUserId;
	}

	public void setMessageUserId(Integer messageUserId) {
		this.messageUserId = messageUserId;
	}
}