package project.edupm.projectmanage.pojo;

import java.util.Date;

public class EduProjectNotrain {
	
	private Integer createByArea;
	public Integer getCreateByArea() {
		return createByArea;
	}

	public void setCreateByArea(Integer createByArea) {
		this.createByArea = createByArea;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.code
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String code;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String name;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.type_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer typeId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.type_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String typeName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.model_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer modelId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.model_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String modelName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.year
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String year;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.credit
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer credit;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.scope_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer scopeId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.scope_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String scopeName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.organizer
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String organizer;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.begin_date
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String beginDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.end_date
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String endDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.property_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer propertyId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.property_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String propertyName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.train_type_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private Integer trainTypeId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.train_type_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String trainTypeName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column edu_project_notrain.description
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	private String description;

	private Integer pid;
	private Integer cid;
	private Integer did;
	private Integer sid;

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Integer getDid() {
		return did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.id
	 * 
	 * @return the value of edu_project_notrain.id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.id
	 * 
	 * @param id
	 *            the value for edu_project_notrain.id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.code
	 * 
	 * @return the value of edu_project_notrain.code
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.code
	 * 
	 * @param code
	 *            the value for edu_project_notrain.code
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.name
	 * 
	 * @return the value of edu_project_notrain.name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.name
	 * 
	 * @param name
	 *            the value for edu_project_notrain.name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.type_id
	 * 
	 * @return the value of edu_project_notrain.type_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.type_id
	 * 
	 * @param typeId
	 *            the value for edu_project_notrain.type_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.type_name
	 * 
	 * @return the value of edu_project_notrain.type_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.type_name
	 * 
	 * @param typeName
	 *            the value for edu_project_notrain.type_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.model_id
	 * 
	 * @return the value of edu_project_notrain.model_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getModelId() {
		return modelId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.model_id
	 * 
	 * @param modelId
	 *            the value for edu_project_notrain.model_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.model_name
	 * 
	 * @return the value of edu_project_notrain.model_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getModelName() {
		return modelName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.model_name
	 * 
	 * @param modelName
	 *            the value for edu_project_notrain.model_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.year
	 * 
	 * @return the value of edu_project_notrain.year
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.year
	 * 
	 * @param year
	 *            the value for edu_project_notrain.year
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.credit
	 * 
	 * @return the value of edu_project_notrain.credit
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getCredit() {
		return credit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.credit
	 * 
	 * @param credit
	 *            the value for edu_project_notrain.credit
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.scope_id
	 * 
	 * @return the value of edu_project_notrain.scope_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getScopeId() {
		return scopeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.scope_id
	 * 
	 * @param scopeId
	 *            the value for edu_project_notrain.scope_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setScopeId(Integer scopeId) {
		this.scopeId = scopeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.scope_name
	 * 
	 * @return the value of edu_project_notrain.scope_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getScopeName() {
		return scopeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.scope_name
	 * 
	 * @param scopeName
	 *            the value for edu_project_notrain.scope_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setScopeName(String scopeName) {
		this.scopeName = scopeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.organizer
	 * 
	 * @return the value of edu_project_notrain.organizer
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getOrganizer() {
		return organizer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.organizer
	 * 
	 * @param organizer
	 *            the value for edu_project_notrain.organizer
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setOrganizer(String organizer) {
		this.organizer = organizer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.begin_date
	 * 
	 * @return the value of edu_project_notrain.begin_date
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getBeginDate() {
		return beginDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.begin_date
	 * 
	 * @param beginDate
	 *            the value for edu_project_notrain.begin_date
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.end_date
	 * 
	 * @return the value of edu_project_notrain.end_date
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.end_date
	 * 
	 * @param endDate
	 *            the value for edu_project_notrain.end_date
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.property_id
	 * 
	 * @return the value of edu_project_notrain.property_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getPropertyId() {
		return propertyId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.property_id
	 * 
	 * @param propertyId
	 *            the value for edu_project_notrain.property_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setPropertyId(Integer propertyId) {
		this.propertyId = propertyId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.property_name
	 * 
	 * @return the value of edu_project_notrain.property_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getPropertyName() {
		return propertyName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.property_name
	 * 
	 * @param propertyName
	 *            the value for edu_project_notrain.property_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.train_type_id
	 * 
	 * @return the value of edu_project_notrain.train_type_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public Integer getTrainTypeId() {
		return trainTypeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.train_type_id
	 * 
	 * @param trainTypeId
	 *            the value for edu_project_notrain.train_type_id
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setTrainTypeId(Integer trainTypeId) {
		this.trainTypeId = trainTypeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.train_type_name
	 * 
	 * @return the value of edu_project_notrain.train_type_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getTrainTypeName() {
		return trainTypeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.train_type_name
	 * 
	 * @param trainTypeName
	 *            the value for edu_project_notrain.train_type_name
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setTrainTypeName(String trainTypeName) {
		this.trainTypeName = trainTypeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column edu_project_notrain.description
	 * 
	 * @return the value of edu_project_notrain.description
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column edu_project_notrain.description
	 * 
	 * @param description
	 *            the value for edu_project_notrain.description
	 * 
	 * @abatorgenerated Fri May 09 10:38:50 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}