package project.teacher.teacherProject.pojo;

import java.util.Date;

public class EduAudit {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.teacher_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_status
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer auditStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_auditor
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String auditAuditor;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Date auditDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_create_by
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String auditCreateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_update_by
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String auditUpdateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_create_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Date auditCreateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_update_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Date auditUpdateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.old_version
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer oldVersion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_version
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer newVersion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.change_type
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer changeType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_province_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer pastProvinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_province_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String pastProvinceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_city_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer pastCityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_city_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String pastCityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_district_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer pastDistrictId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_district_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String pastDistrictName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_school_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer pastSchoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.past_school_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String pastSchoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_province_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer newProvinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_province_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String newProvinceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_city_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer newCityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_city_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String newCityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_district_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer newDistrictId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_district_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String newDistrictName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_school_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private Integer newSchoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.new_school_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String newSchoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_audit.audit_option
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    private String auditOption;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.id
     *
     * @return the value of edu_audit.id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.id
     *
     * @param id the value for edu_audit.id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.teacher_id
     *
     * @return the value of edu_audit.teacher_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.teacher_id
     *
     * @param teacherId the value for edu_audit.teacher_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_status
     *
     * @return the value of edu_audit.audit_status
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_status
     *
     * @param auditStatus the value for edu_audit.audit_status
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_auditor
     *
     * @return the value of edu_audit.audit_auditor
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getAuditAuditor() {
        return auditAuditor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_auditor
     *
     * @param auditAuditor the value for edu_audit.audit_auditor
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditAuditor(String auditAuditor) {
        this.auditAuditor = auditAuditor;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_date
     *
     * @return the value of edu_audit.audit_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_date
     *
     * @param auditDate the value for edu_audit.audit_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_create_by
     *
     * @return the value of edu_audit.audit_create_by
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getAuditCreateBy() {
        return auditCreateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_create_by
     *
     * @param auditCreateBy the value for edu_audit.audit_create_by
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditCreateBy(String auditCreateBy) {
        this.auditCreateBy = auditCreateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_update_by
     *
     * @return the value of edu_audit.audit_update_by
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getAuditUpdateBy() {
        return auditUpdateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_update_by
     *
     * @param auditUpdateBy the value for edu_audit.audit_update_by
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditUpdateBy(String auditUpdateBy) {
        this.auditUpdateBy = auditUpdateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_create_date
     *
     * @return the value of edu_audit.audit_create_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Date getAuditCreateDate() {
        return auditCreateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_create_date
     *
     * @param auditCreateDate the value for edu_audit.audit_create_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditCreateDate(Date auditCreateDate) {
        this.auditCreateDate = auditCreateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_update_date
     *
     * @return the value of edu_audit.audit_update_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Date getAuditUpdateDate() {
        return auditUpdateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_update_date
     *
     * @param auditUpdateDate the value for edu_audit.audit_update_date
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditUpdateDate(Date auditUpdateDate) {
        this.auditUpdateDate = auditUpdateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.old_version
     *
     * @return the value of edu_audit.old_version
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getOldVersion() {
        return oldVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.old_version
     *
     * @param oldVersion the value for edu_audit.old_version
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setOldVersion(Integer oldVersion) {
        this.oldVersion = oldVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_version
     *
     * @return the value of edu_audit.new_version
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getNewVersion() {
        return newVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_version
     *
     * @param newVersion the value for edu_audit.new_version
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewVersion(Integer newVersion) {
        this.newVersion = newVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.change_type
     *
     * @return the value of edu_audit.change_type
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.change_type
     *
     * @param changeType the value for edu_audit.change_type
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setChangeType(Integer changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_province_id
     *
     * @return the value of edu_audit.past_province_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getPastProvinceId() {
        return pastProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_province_id
     *
     * @param pastProvinceId the value for edu_audit.past_province_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastProvinceId(Integer pastProvinceId) {
        this.pastProvinceId = pastProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_province_name
     *
     * @return the value of edu_audit.past_province_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getPastProvinceName() {
        return pastProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_province_name
     *
     * @param pastProvinceName the value for edu_audit.past_province_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastProvinceName(String pastProvinceName) {
        this.pastProvinceName = pastProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_city_id
     *
     * @return the value of edu_audit.past_city_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getPastCityId() {
        return pastCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_city_id
     *
     * @param pastCityId the value for edu_audit.past_city_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastCityId(Integer pastCityId) {
        this.pastCityId = pastCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_city_name
     *
     * @return the value of edu_audit.past_city_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getPastCityName() {
        return pastCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_city_name
     *
     * @param pastCityName the value for edu_audit.past_city_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastCityName(String pastCityName) {
        this.pastCityName = pastCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_district_id
     *
     * @return the value of edu_audit.past_district_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getPastDistrictId() {
        return pastDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_district_id
     *
     * @param pastDistrictId the value for edu_audit.past_district_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastDistrictId(Integer pastDistrictId) {
        this.pastDistrictId = pastDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_district_name
     *
     * @return the value of edu_audit.past_district_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getPastDistrictName() {
        return pastDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_district_name
     *
     * @param pastDistrictName the value for edu_audit.past_district_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastDistrictName(String pastDistrictName) {
        this.pastDistrictName = pastDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_school_id
     *
     * @return the value of edu_audit.past_school_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getPastSchoolId() {
        return pastSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_school_id
     *
     * @param pastSchoolId the value for edu_audit.past_school_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastSchoolId(Integer pastSchoolId) {
        this.pastSchoolId = pastSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.past_school_name
     *
     * @return the value of edu_audit.past_school_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getPastSchoolName() {
        return pastSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.past_school_name
     *
     * @param pastSchoolName the value for edu_audit.past_school_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setPastSchoolName(String pastSchoolName) {
        this.pastSchoolName = pastSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_province_id
     *
     * @return the value of edu_audit.new_province_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getNewProvinceId() {
        return newProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_province_id
     *
     * @param newProvinceId the value for edu_audit.new_province_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewProvinceId(Integer newProvinceId) {
        this.newProvinceId = newProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_province_name
     *
     * @return the value of edu_audit.new_province_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getNewProvinceName() {
        return newProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_province_name
     *
     * @param newProvinceName the value for edu_audit.new_province_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewProvinceName(String newProvinceName) {
        this.newProvinceName = newProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_city_id
     *
     * @return the value of edu_audit.new_city_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getNewCityId() {
        return newCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_city_id
     *
     * @param newCityId the value for edu_audit.new_city_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewCityId(Integer newCityId) {
        this.newCityId = newCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_city_name
     *
     * @return the value of edu_audit.new_city_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getNewCityName() {
        return newCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_city_name
     *
     * @param newCityName the value for edu_audit.new_city_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewCityName(String newCityName) {
        this.newCityName = newCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_district_id
     *
     * @return the value of edu_audit.new_district_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getNewDistrictId() {
        return newDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_district_id
     *
     * @param newDistrictId the value for edu_audit.new_district_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewDistrictId(Integer newDistrictId) {
        this.newDistrictId = newDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_district_name
     *
     * @return the value of edu_audit.new_district_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getNewDistrictName() {
        return newDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_district_name
     *
     * @param newDistrictName the value for edu_audit.new_district_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewDistrictName(String newDistrictName) {
        this.newDistrictName = newDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_school_id
     *
     * @return the value of edu_audit.new_school_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public Integer getNewSchoolId() {
        return newSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_school_id
     *
     * @param newSchoolId the value for edu_audit.new_school_id
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewSchoolId(Integer newSchoolId) {
        this.newSchoolId = newSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.new_school_name
     *
     * @return the value of edu_audit.new_school_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getNewSchoolName() {
        return newSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.new_school_name
     *
     * @param newSchoolName the value for edu_audit.new_school_name
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setNewSchoolName(String newSchoolName) {
        this.newSchoolName = newSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_audit.audit_option
     *
     * @return the value of edu_audit.audit_option
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public String getAuditOption() {
        return auditOption;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_audit.audit_option
     *
     * @param auditOption the value for edu_audit.audit_option
     *
     * @abatorgenerated Tue Apr 15 14:17:23 CST 2014
     */
    public void setAuditOption(String auditOption) {
        this.auditOption = auditOption;
    }
    
    private String mobilizeMark;

	public String getMobilizeMark() {
		return mobilizeMark;
	}

	public void setMobilizeMark(String mobilizeMark) {
		this.mobilizeMark = mobilizeMark;
	}
    
}