package project.teacher.teacherProject.pojo;

import java.util.Date;

public class EduTeacherOldSchool {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.id
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.teacher_id
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.old_school
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private String oldSchool;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.old_entry_time
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Date oldEntryTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.old_turnover_time
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Date oldTurnoverTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.create_by
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.update_by
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.create_date
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.update_date
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_teacher_old_school.version
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.id
     *
     * @return the value of edu_teacher_old_school.id
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.id
     *
     * @param id the value for edu_teacher_old_school.id
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.teacher_id
     *
     * @return the value of edu_teacher_old_school.teacher_id
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.teacher_id
     *
     * @param teacherId the value for edu_teacher_old_school.teacher_id
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.old_school
     *
     * @return the value of edu_teacher_old_school.old_school
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public String getOldSchool() {
        return oldSchool;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.old_school
     *
     * @param oldSchool the value for edu_teacher_old_school.old_school
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setOldSchool(String oldSchool) {
        this.oldSchool = oldSchool;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.old_entry_time
     *
     * @return the value of edu_teacher_old_school.old_entry_time
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Date getOldEntryTime() {
        return oldEntryTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.old_entry_time
     *
     * @param oldEntryTime the value for edu_teacher_old_school.old_entry_time
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setOldEntryTime(Date oldEntryTime) {
        this.oldEntryTime = oldEntryTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.old_turnover_time
     *
     * @return the value of edu_teacher_old_school.old_turnover_time
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Date getOldTurnoverTime() {
        return oldTurnoverTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.old_turnover_time
     *
     * @param oldTurnoverTime the value for edu_teacher_old_school.old_turnover_time
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setOldTurnoverTime(Date oldTurnoverTime) {
        this.oldTurnoverTime = oldTurnoverTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.create_by
     *
     * @return the value of edu_teacher_old_school.create_by
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.create_by
     *
     * @param createBy the value for edu_teacher_old_school.create_by
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.update_by
     *
     * @return the value of edu_teacher_old_school.update_by
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.update_by
     *
     * @param updateBy the value for edu_teacher_old_school.update_by
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.create_date
     *
     * @return the value of edu_teacher_old_school.create_date
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.create_date
     *
     * @param createDate the value for edu_teacher_old_school.create_date
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.update_date
     *
     * @return the value of edu_teacher_old_school.update_date
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.update_date
     *
     * @param updateDate the value for edu_teacher_old_school.update_date
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_teacher_old_school.version
     *
     * @return the value of edu_teacher_old_school.version
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_teacher_old_school.version
     *
     * @param version the value for edu_teacher_old_school.version
     *
     * @abatorgenerated Fri Mar 28 17:14:36 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}