package project.teacher.teacherProject.pojo;

import java.util.Date;

public class EduUserPojo {
    private Integer id;
    private String loginAccount;
    private String realName;
    private Integer roleId;
    private String idNumber;
    private String mail;
    private String mobile;
    private Integer paswdQuestionType;
    private String paswdAnswer;
    private String password;
    private String createBy;
    private String updateBy;
    private Date createDate;
    private Date updateDate;
    private Integer status;
    private Integer version;
    private String teacherNo;
    private Integer schoolId;
    private Integer gender;
    private String schoolName;
    private String userImageUrl;
    public String getUserImageUrl() {
		return userImageUrl;
	}
	public void setUserImageUrl(String userImageUrl) {
		this.userImageUrl = userImageUrl;
	}
	public String getSchoolName() {
		return schoolName;
	}
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}
	public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLoginAccount() {
        return loginAccount;
    }

    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }
    public String getRealName() {
        return realName;
    }
    public void setRealName(String realName) {
        this.realName = realName;
    }
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.role_id
     *
     * @param roleId the value for edu_user.role_id
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.id_number
     *
     * @return the value of edu_user.id_number
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.id_number
     *
     * @param idNumber the value for edu_user.id_number
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.mail
     *
     * @return the value of edu_user.mail
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.mail
     *
     * @param mail the value for edu_user.mail
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.mobile
     *
     * @return the value of edu_user.mobile
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.mobile
     *
     * @param mobile the value for edu_user.mobile
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.paswd_question_type
     *
     * @return the value of edu_user.paswd_question_type
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Integer getPaswdQuestionType() {
        return paswdQuestionType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.paswd_question_type
     *
     * @param paswdQuestionType the value for edu_user.paswd_question_type
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setPaswdQuestionType(Integer paswdQuestionType) {
        this.paswdQuestionType = paswdQuestionType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.paswd_answer
     *
     * @return the value of edu_user.paswd_answer
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getPaswdAnswer() {
        return paswdAnswer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.paswd_answer
     *
     * @param paswdAnswer the value for edu_user.paswd_answer
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setPaswdAnswer(String paswdAnswer) {
        this.paswdAnswer = paswdAnswer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.password
     *
     * @return the value of edu_user.password
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.password
     *
     * @param password the value for edu_user.password
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.create_by
     *
     * @return the value of edu_user.create_by
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.create_by
     *
     * @param createBy the value for edu_user.create_by
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.update_by
     *
     * @return the value of edu_user.update_by
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.update_by
     *
     * @param updateBy the value for edu_user.update_by
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.create_date
     *
     * @return the value of edu_user.create_date
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.create_date
     *
     * @param createDate the value for edu_user.create_date
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.update_date
     *
     * @return the value of edu_user.update_date
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.update_date
     *
     * @param updateDate the value for edu_user.update_date
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.status
     *
     * @return the value of edu_user.status
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.status
     *
     * @param status the value for edu_user.status
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.version
     *
     * @return the value of edu_user.version
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.version
     *
     * @param version the value for edu_user.version
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.teacher_no
     *
     * @return the value of edu_user.teacher_no
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public String getTeacherNo() {
        return teacherNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.teacher_no
     *
     * @param teacherNo the value for edu_user.teacher_no
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setTeacherNo(String teacherNo) {
        this.teacherNo = teacherNo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.school_id
     *
     * @return the value of edu_user.school_id
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.school_id
     *
     * @param schoolId the value for edu_user.school_id
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_user.gender
     *
     * @return the value of edu_user.gender
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_user.gender
     *
     * @param gender the value for edu_user.gender
     *
     * @abatorgenerated Thu Mar 27 21:04:58 CST 2014
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }
}