package project.furtheredu.eduTarget.pojo;

import java.util.Date;

public class EduTargetByYear {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.year
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String year;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.class_period
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String classPeriod;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.class_score
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String classScore;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.status
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.province_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Integer provinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.province_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String provinceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.city_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Integer cityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.city_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String cityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.district_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Integer districtId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.district_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String districtName;
    
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.create_by
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.create_date
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.update_by
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_target_by_year.update_date
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.id
     *
     * @return the value of edu_target_by_year.id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.id
     *
     * @param id the value for edu_target_by_year.id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.year
     *
     * @return the value of edu_target_by_year.year
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.year
     *
     * @param year the value for edu_target_by_year.year
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.class_period
     *
     * @return the value of edu_target_by_year.class_period
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getClassPeriod() {
        return classPeriod;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.class_period
     *
     * @param classPeriod the value for edu_target_by_year.class_period
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setClassPeriod(String classPeriod) {
        this.classPeriod = classPeriod;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.class_score
     *
     * @return the value of edu_target_by_year.class_score
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getClassScore() {
        return classScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.class_score
     *
     * @param classScore the value for edu_target_by_year.class_score
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setClassScore(String classScore) {
        this.classScore = classScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.status
     *
     * @return the value of edu_target_by_year.status
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.status
     *
     * @param status the value for edu_target_by_year.status
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.province_id
     *
     * @return the value of edu_target_by_year.province_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.province_id
     *
     * @param provinceId the value for edu_target_by_year.province_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.province_name
     *
     * @return the value of edu_target_by_year.province_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.province_name
     *
     * @param provinceName the value for edu_target_by_year.province_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.city_id
     *
     * @return the value of edu_target_by_year.city_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.city_id
     *
     * @param cityId the value for edu_target_by_year.city_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.city_name
     *
     * @return the value of edu_target_by_year.city_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.city_name
     *
     * @param cityName the value for edu_target_by_year.city_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.district_id
     *
     * @return the value of edu_target_by_year.district_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.district_id
     *
     * @param districtId the value for edu_target_by_year.district_id
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.district_name
     *
     * @return the value of edu_target_by_year.district_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.district_name
     *
     * @param districtName the value for edu_target_by_year.district_name
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.create_by
     *
     * @return the value of edu_target_by_year.create_by
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.create_by
     *
     * @param createBy the value for edu_target_by_year.create_by
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.create_date
     *
     * @return the value of edu_target_by_year.create_date
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.create_date
     *
     * @param createDate the value for edu_target_by_year.create_date
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.update_by
     *
     * @return the value of edu_target_by_year.update_by
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.update_by
     *
     * @param updateBy the value for edu_target_by_year.update_by
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_target_by_year.update_date
     *
     * @return the value of edu_target_by_year.update_date
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_target_by_year.update_date
     *
     * @param updateDate the value for edu_target_by_year.update_date
     *
     * @abatorgenerated Sat Mar 29 23:56:40 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    
    private Integer schoolId;
    private String schoolName;
    private Integer type;

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public String getSchoolName() {
		return schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}
    
}