package project.edupm.projectclass.pojo;

import java.util.Date;

public class EduProjectClass {
	
	private String classSubjectName;
	private String classSubjectId;
	
	private Integer roleId;
	
	private Integer userId;
	
    public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getClassSubjectId() {
		return classSubjectId;
	}

	public void setClassSubjectId(String classSubjectId) {
		this.classSubjectId = classSubjectId;
	}

	public String getClassSubjectName() {
		return classSubjectName;
	}

	public void setClassSubjectName(String classSubjectName) {
		this.classSubjectName = classSubjectName;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.id
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.class_name
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private String className;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.class_type
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private String classType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.class_type_id
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private Integer classTypeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.class_url
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private String classUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.status
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.create_by
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.update_by
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.create_date
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.update_date
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_class.memo
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    private String memo;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.id
     *
     * @return the value of edu_project_class.id
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.id
     *
     * @param id the value for edu_project_class.id
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.class_name
     *
     * @return the value of edu_project_class.class_name
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.class_name
     *
     * @param className the value for edu_project_class.class_name
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.class_type
     *
     * @return the value of edu_project_class.class_type
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.class_type
     *
     * @param classType the value for edu_project_class.class_type
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setClassType(String classType) {
        this.classType = classType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.class_type_id
     *
     * @return the value of edu_project_class.class_type_id
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public Integer getClassTypeId() {
        return classTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.class_type_id
     *
     * @param classTypeId the value for edu_project_class.class_type_id
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setClassTypeId(Integer classTypeId) {
        this.classTypeId = classTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.class_url
     *
     * @return the value of edu_project_class.class_url
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public String getClassUrl() {
        return classUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.class_url
     *
     * @param classUrl the value for edu_project_class.class_url
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setClassUrl(String classUrl) {
        this.classUrl = classUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.status
     *
     * @return the value of edu_project_class.status
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.status
     *
     * @param status the value for edu_project_class.status
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.create_by
     *
     * @return the value of edu_project_class.create_by
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.create_by
     *
     * @param createBy the value for edu_project_class.create_by
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.update_by
     *
     * @return the value of edu_project_class.update_by
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.update_by
     *
     * @param updateBy the value for edu_project_class.update_by
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.create_date
     *
     * @return the value of edu_project_class.create_date
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.create_date
     *
     * @param createDate the value for edu_project_class.create_date
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.update_date
     *
     * @return the value of edu_project_class.update_date
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.update_date
     *
     * @param updateDate the value for edu_project_class.update_date
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_class.memo
     *
     * @return the value of edu_project_class.memo
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_class.memo
     *
     * @param memo the value for edu_project_class.memo
     *
     * @abatorgenerated Mon Mar 31 15:10:29 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}