package project.edupm.projectmanage.pojo;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * 项目审核
 * @author zhangBo
 *
 */
public class EduProjectAuditPOJO {
    private Integer id;

    private Integer auditorId;
    
    private Integer projectId;

    private Integer applicantId;

    private String auditorRealName;

    private Date auditDate;

    private Integer auditStatus;

    private String createBy;

    private Date createDate;

    private String memo;
    
    private Date updateDate;
    private String updateBy;
    
    private String status;

    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}


	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.id
     *
     * @param id the value for edu_project_audit.id
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.auditor_id
     *
     * @return the value of edu_project_audit.auditor_id
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public Integer getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.auditor_id
     *
     * @param auditorId the value for edu_project_audit.auditor_id
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setAuditorId(Integer auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.applicant_id
     *
     * @return the value of edu_project_audit.applicant_id
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public Integer getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.applicant_id
     *
     * @param applicantId the value for edu_project_audit.applicant_id
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setApplicantId(Integer applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.auditor_real_name
     *
     * @return the value of edu_project_audit.auditor_real_name
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public String getAuditorRealName() {
        return auditorRealName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.auditor_real_name
     *
     * @param auditorRealName the value for edu_project_audit.auditor_real_name
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setAuditorRealName(String auditorRealName) {
        this.auditorRealName = auditorRealName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.audit_date
     *
     * @return the value of edu_project_audit.audit_date
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public String getAuditDate() {
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return auditDate==null?null:sdf.format(auditDate);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.audit_date
     *
     * @param auditDate the value for edu_project_audit.audit_date
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.audit_status
     *
     * @return the value of edu_project_audit.audit_status
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.audit_status
     *
     * @param auditStatus the value for edu_project_audit.audit_status
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.create_by
     *
     * @return the value of edu_project_audit.create_by
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.create_by
     *
     * @param createBy the value for edu_project_audit.create_by
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.create_date
     *
     * @return the value of edu_project_audit.create_date
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.create_date
     *
     * @param createDate the value for edu_project_audit.create_date
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_audit.memo
     *
     * @return the value of edu_project_audit.memo
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_audit.memo
     *
     * @param memo the value for edu_project_audit.memo
     *
     * @abatorgenerated Sat Apr 26 21:49:06 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}