package project.statistic.pojo;

public class EduStatisticModel {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_statistic_model.id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    private Integer id;
    
    public String getSchoolName() {
		return schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	private String schoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_statistic_model.model_id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    private Integer modelId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_statistic_model.model_name
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    private String modelName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_statistic_model.teacher_id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_statistic_model.teacher_name
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    private String teacherName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_statistic_model.teacher_score
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    private Float teacherScore;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_statistic_model.id
     *
     * @return the value of edu_statistic_model.id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_statistic_model.id
     *
     * @param id the value for edu_statistic_model.id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_statistic_model.model_id
     *
     * @return the value of edu_statistic_model.model_id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_statistic_model.model_id
     *
     * @param modelId the value for edu_statistic_model.model_id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_statistic_model.model_name
     *
     * @return the value of edu_statistic_model.model_name
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_statistic_model.model_name
     *
     * @param modelName the value for edu_statistic_model.model_name
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_statistic_model.teacher_id
     *
     * @return the value of edu_statistic_model.teacher_id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_statistic_model.teacher_id
     *
     * @param teacherId the value for edu_statistic_model.teacher_id
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_statistic_model.teacher_name
     *
     * @return the value of edu_statistic_model.teacher_name
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_statistic_model.teacher_name
     *
     * @param teacherName the value for edu_statistic_model.teacher_name
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_statistic_model.teacher_score
     *
     * @return the value of edu_statistic_model.teacher_score
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public Float getTeacherScore() {
        return teacherScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_statistic_model.teacher_score
     *
     * @param teacherScore the value for edu_statistic_model.teacher_score
     *
     * @abatorgenerated Fri May 09 10:38:16 CST 2014
     */
    public void setTeacherScore(Float teacherScore) {
        this.teacherScore = teacherScore;
    }
}