package project.edupm.projectmanage.pojo;

import java.util.Date;

public class EduProjectSummary {
	private Integer summaryId;
	
	public Integer getSummaryId() {
		return summaryId;
	}

	public void setSummaryId(Integer summaryId) {
		this.summaryId = summaryId;
	}
	private String orgName;
	
    public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	private Integer orgType;

	public Integer getOrgType() {
		return orgType;
	}

	public void setOrgType(Integer orgType) {
		this.orgType = orgType;
	}
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.id
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.project_id
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.type
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.title
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.attchement_title
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private String attchementTitle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.attchement_url
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private String attchementUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.create_date
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.create_by
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private Integer createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_summary.content
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    private String content;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.id
     *
     * @return the value of edu_project_summary.id
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.id
     *
     * @param id the value for edu_project_summary.id
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.project_id
     *
     * @return the value of edu_project_summary.project_id
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.project_id
     *
     * @param projectId the value for edu_project_summary.project_id
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.type
     *
     * @return the value of edu_project_summary.type
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.type
     *
     * @param type the value for edu_project_summary.type
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.title
     *
     * @return the value of edu_project_summary.title
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.title
     *
     * @param title the value for edu_project_summary.title
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.attchement_title
     *
     * @return the value of edu_project_summary.attchement_title
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public String getAttchementTitle() {
        return attchementTitle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.attchement_title
     *
     * @param attchementTitle the value for edu_project_summary.attchement_title
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setAttchementTitle(String attchementTitle) {
        this.attchementTitle = attchementTitle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.attchement_url
     *
     * @return the value of edu_project_summary.attchement_url
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public String getAttchementUrl() {
        return attchementUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.attchement_url
     *
     * @param attchementUrl the value for edu_project_summary.attchement_url
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setAttchementUrl(String attchementUrl) {
        this.attchementUrl = attchementUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.create_date
     *
     * @return the value of edu_project_summary.create_date
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.create_date
     *
     * @param createDate the value for edu_project_summary.create_date
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.create_by
     *
     * @return the value of edu_project_summary.create_by
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.create_by
     *
     * @param createBy the value for edu_project_summary.create_by
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_summary.content
     *
     * @return the value of edu_project_summary.content
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_summary.content
     *
     * @param content the value for edu_project_summary.content
     *
     * @abatorgenerated Sat Apr 26 14:28:23 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}