package project.edupm.projectmanage.pojo;

import java.util.Date;

public class EduProjectNotrainComment {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.project_id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.teacher_id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.teacher_score
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Float teacherScore;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.audit_score
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Float auditScore;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.audit_status
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Integer auditStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.audit_status_name
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private String auditStatusName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.create_by
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.create_date
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.update_by
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_project_notrain_comment.update_date
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    private Date updateDate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.id
     *
     * @return the value of edu_project_notrain_comment.id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.id
     *
     * @param id the value for edu_project_notrain_comment.id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.project_id
     *
     * @return the value of edu_project_notrain_comment.project_id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.project_id
     *
     * @param projectId the value for edu_project_notrain_comment.project_id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.teacher_id
     *
     * @return the value of edu_project_notrain_comment.teacher_id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.teacher_id
     *
     * @param teacherId the value for edu_project_notrain_comment.teacher_id
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.teacher_score
     *
     * @return the value of edu_project_notrain_comment.teacher_score
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Float getTeacherScore() {
        return teacherScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.teacher_score
     *
     * @param teacherScore the value for edu_project_notrain_comment.teacher_score
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setTeacherScore(Float teacherScore) {
        this.teacherScore = teacherScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.audit_score
     *
     * @return the value of edu_project_notrain_comment.audit_score
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Float getTacherAudiScore() {
        return auditScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.audit_score
     *
     * @param tacherAudiScore the value for edu_project_notrain_comment.audit_score
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setTacherAudiScore(Float tacherAudiScore) {
        this.auditScore = tacherAudiScore;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.audit_status
     *
     * @return the value of edu_project_notrain_comment.audit_status
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.audit_status
     *
     * @param auditStatus the value for edu_project_notrain_comment.audit_status
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.audit_status_name
     *
     * @return the value of edu_project_notrain_comment.audit_status_name
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public String getAuditStatusName() {
        return auditStatusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.audit_status_name
     *
     * @param auditStatusName the value for edu_project_notrain_comment.audit_status_name
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setAuditStatusName(String auditStatusName) {
        this.auditStatusName = auditStatusName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.create_by
     *
     * @return the value of edu_project_notrain_comment.create_by
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.create_by
     *
     * @param createBy the value for edu_project_notrain_comment.create_by
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.create_date
     *
     * @return the value of edu_project_notrain_comment.create_date
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.create_date
     *
     * @param createDate the value for edu_project_notrain_comment.create_date
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.update_by
     *
     * @return the value of edu_project_notrain_comment.update_by
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.update_by
     *
     * @param updateBy the value for edu_project_notrain_comment.update_by
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_notrain_comment.update_date
     *
     * @return the value of edu_project_notrain_comment.update_date
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_notrain_comment.update_date
     *
     * @param updateDate the value for edu_project_notrain_comment.update_date
     *
     * @abatorgenerated Fri May 09 10:38:39 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}