package project.edupm.projectmanage.pojo;

public class EduProjectTrainTarget {
	
    private Integer id;

    private Integer gradeId;

    private String gradeName;

    private String sex;

    private Integer educationBackgroundId;

    private String educationBackgroundName;

    private Integer positionId;

    private String positionName;

    private Integer professionalTitleId;

    private String isClassCharger;

    private String subjectId;

    private String subjectName;

    private String stdutySectionId;

    private String stdutySection;

    private String isFree;

    private String mustAudit;

    private String chargingStandard;

    private Integer projectId;

    private String professionalTitleName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.id
     *
     * @return the value of edu_project_train_target.id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.id
     *
     * @param id the value for edu_project_train_target.id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.grade_id
     *
     * @return the value of edu_project_train_target.grade_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.grade_id
     *
     * @param gradeId the value for edu_project_train_target.grade_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.grade_name
     *
     * @return the value of edu_project_train_target.grade_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.grade_name
     *
     * @param gradeName the value for edu_project_train_target.grade_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.sex
     *
     * @return the value of edu_project_train_target.sex
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.sex
     *
     * @param sex the value for edu_project_train_target.sex
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.education_background_id
     *
     * @return the value of edu_project_train_target.education_background_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public Integer getEducationBackgroundId() {
        return educationBackgroundId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.education_background_id
     *
     * @param educationBackgroundId the value for edu_project_train_target.education_background_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setEducationBackgroundId(Integer educationBackgroundId) {
        this.educationBackgroundId = educationBackgroundId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.education_background_name
     *
     * @return the value of edu_project_train_target.education_background_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getEducationBackgroundName() {
        return educationBackgroundName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.education_background_name
     *
     * @param educationBackgroundName the value for edu_project_train_target.education_background_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setEducationBackgroundName(String educationBackgroundName) {
        this.educationBackgroundName = educationBackgroundName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.position_id
     *
     * @return the value of edu_project_train_target.position_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.position_id
     *
     * @param positionId the value for edu_project_train_target.position_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.position_name
     *
     * @return the value of edu_project_train_target.position_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.position_name
     *
     * @param positionName the value for edu_project_train_target.position_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.professional_title_id
     *
     * @return the value of edu_project_train_target.professional_title_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public Integer getProfessionalTitleId() {
        return professionalTitleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.professional_title_id
     *
     * @param professionalTitleId the value for edu_project_train_target.professional_title_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setProfessionalTitleId(Integer professionalTitleId) {
        this.professionalTitleId = professionalTitleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.is_class_charger
     *
     * @return the value of edu_project_train_target.is_class_charger
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getIsClassCharger() {
        return isClassCharger;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.is_class_charger
     *
     * @param isClassCharger the value for edu_project_train_target.is_class_charger
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setIsClassCharger(String isClassCharger) {
        this.isClassCharger = isClassCharger;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.subject_id
     *
     * @return the value of edu_project_train_target.subject_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.subject_id
     *
     * @param subjectId the value for edu_project_train_target.subject_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.subject_name
     *
     * @return the value of edu_project_train_target.subject_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.subject_name
     *
     * @param subjectName the value for edu_project_train_target.subject_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.stduty_section_id
     *
     * @return the value of edu_project_train_target.stduty_section_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getStdutySectionId() {
        return stdutySectionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.stduty_section_id
     *
     * @param stdutySectionId the value for edu_project_train_target.stduty_section_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setStdutySectionId(String stdutySectionId) {
        this.stdutySectionId = stdutySectionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.stduty_section
     *
     * @return the value of edu_project_train_target.stduty_section
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getStdutySection() {
        return stdutySection;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.stduty_section
     *
     * @param stdutySection the value for edu_project_train_target.stduty_section
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setStdutySection(String stdutySection) {
        this.stdutySection = stdutySection;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.is_free
     *
     * @return the value of edu_project_train_target.is_free
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.is_free
     *
     * @param isFree the value for edu_project_train_target.is_free
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setIsFree(String isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.must_audit
     *
     * @return the value of edu_project_train_target.must_audit
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getMustAudit() {
        return mustAudit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.must_audit
     *
     * @param mustAudit the value for edu_project_train_target.must_audit
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setMustAudit(String mustAudit) {
        this.mustAudit = mustAudit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.charging_standard
     *
     * @return the value of edu_project_train_target.charging_standard
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getChargingStandard() {
        return chargingStandard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.charging_standard
     *
     * @param chargingStandard the value for edu_project_train_target.charging_standard
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setChargingStandard(String chargingStandard) {
        this.chargingStandard = chargingStandard;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.project_id
     *
     * @return the value of edu_project_train_target.project_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.project_id
     *
     * @param projectId the value for edu_project_train_target.project_id
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_train_target.professional_title_name
     *
     * @return the value of edu_project_train_target.professional_title_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public String getProfessionalTitleName() {
        return professionalTitleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_train_target.professional_title_name
     *
     * @param professionalTitleName the value for edu_project_train_target.professional_title_name
     *
     * @abatorgenerated Fri Mar 28 10:29:41 CST 2014
     */
    public void setProfessionalTitleName(String professionalTitleName) {
        this.professionalTitleName = professionalTitleName;
    }
}