package project.edupm.projectmanage.pojo;

public class EduProjectAllocateByArea {
	
    private Integer id;

    private Integer projectId;

    private Integer areaId;

    private Integer status;

    private Integer allocatePlanNum;

    private Integer allocateFactNum;

    private String memo;
    
    private String areaName;
    
    private int type;
    
    

    public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.id
     *
     * @return the value of edu_project_allocate_by_area.id
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.id
     *
     * @param id the value for edu_project_allocate_by_area.id
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.project_id
     *
     * @return the value of edu_project_allocate_by_area.project_id
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.project_id
     *
     * @param projectId the value for edu_project_allocate_by_area.project_id
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.area_id
     *
     * @return the value of edu_project_allocate_by_area.area_id
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.area_id
     *
     * @param areaId the value for edu_project_allocate_by_area.area_id
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.status
     *
     * @return the value of edu_project_allocate_by_area.status
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.status
     *
     * @param status the value for edu_project_allocate_by_area.status
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.allocate_plan_num
     *
     * @return the value of edu_project_allocate_by_area.allocate_plan_num
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public Integer getAllocatePlanNum() {
        return allocatePlanNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.allocate_plan_num
     *
     * @param allocatePlanNum the value for edu_project_allocate_by_area.allocate_plan_num
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setAllocatePlanNum(Integer allocatePlanNum) {
        this.allocatePlanNum = allocatePlanNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.allocate_fact_num
     *
     * @return the value of edu_project_allocate_by_area.allocate_fact_num
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public Integer getAllocateFactNum() {
        return allocateFactNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.allocate_fact_num
     *
     * @param allocateFactNum the value for edu_project_allocate_by_area.allocate_fact_num
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setAllocateFactNum(Integer allocateFactNum) {
        this.allocateFactNum = allocateFactNum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_project_allocate_by_area.memo
     *
     * @return the value of edu_project_allocate_by_area.memo
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_project_allocate_by_area.memo
     *
     * @param memo the value for edu_project_allocate_by_area.memo
     *
     * @abatorgenerated Sun Apr 27 16:05:53 CST 2014
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}