package project.teacher.teachermanage.pojo;


import java.util.Date;

public class EduJobtransferHistory {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.teacher_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_province_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer pastProvinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_province_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String pastProvinceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_city_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer pastCityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_city_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String pastCityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_district_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String pastDistrictName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_district_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer pastDistrictId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_school_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer pastSchoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.past_school_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String pastSchoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_proivnce_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String newProivnceName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_province_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer newProvinceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_city_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer newCityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_city_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String newCityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_district_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer newDistrictId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_district_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String newDistrictName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_school_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String newSchoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_school_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer newSchoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.create_by
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.create_date
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.old_version
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer oldVersion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column edu_jobtransfer_history.new_version
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    private Integer newVersion;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.id
     *
     * @return the value of edu_jobtransfer_history.id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.id
     *
     * @param id the value for edu_jobtransfer_history.id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.teacher_id
     *
     * @return the value of edu_jobtransfer_history.teacher_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.teacher_id
     *
     * @param teacherId the value for edu_jobtransfer_history.teacher_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_province_id
     *
     * @return the value of edu_jobtransfer_history.past_province_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getPastProvinceId() {
        return pastProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_province_id
     *
     * @param pastProvinceId the value for edu_jobtransfer_history.past_province_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastProvinceId(Integer pastProvinceId) {
        this.pastProvinceId = pastProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_province_name
     *
     * @return the value of edu_jobtransfer_history.past_province_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getPastProvinceName() {
        return pastProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_province_name
     *
     * @param pastProvinceName the value for edu_jobtransfer_history.past_province_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastProvinceName(String pastProvinceName) {
        this.pastProvinceName = pastProvinceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_city_id
     *
     * @return the value of edu_jobtransfer_history.past_city_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getPastCityId() {
        return pastCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_city_id
     *
     * @param pastCityId the value for edu_jobtransfer_history.past_city_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastCityId(Integer pastCityId) {
        this.pastCityId = pastCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_city_name
     *
     * @return the value of edu_jobtransfer_history.past_city_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getPastCityName() {
        return pastCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_city_name
     *
     * @param pastCityName the value for edu_jobtransfer_history.past_city_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastCityName(String pastCityName) {
        this.pastCityName = pastCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_district_name
     *
     * @return the value of edu_jobtransfer_history.past_district_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getPastDistrictName() {
        return pastDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_district_name
     *
     * @param pastDistrictName the value for edu_jobtransfer_history.past_district_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastDistrictName(String pastDistrictName) {
        this.pastDistrictName = pastDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_district_id
     *
     * @return the value of edu_jobtransfer_history.past_district_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getPastDistrictId() {
        return pastDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_district_id
     *
     * @param pastDistrictId the value for edu_jobtransfer_history.past_district_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastDistrictId(Integer pastDistrictId) {
        this.pastDistrictId = pastDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_school_id
     *
     * @return the value of edu_jobtransfer_history.past_school_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getPastSchoolId() {
        return pastSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_school_id
     *
     * @param pastSchoolId the value for edu_jobtransfer_history.past_school_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastSchoolId(Integer pastSchoolId) {
        this.pastSchoolId = pastSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.past_school_name
     *
     * @return the value of edu_jobtransfer_history.past_school_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getPastSchoolName() {
        return pastSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.past_school_name
     *
     * @param pastSchoolName the value for edu_jobtransfer_history.past_school_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setPastSchoolName(String pastSchoolName) {
        this.pastSchoolName = pastSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_proivnce_name
     *
     * @return the value of edu_jobtransfer_history.new_proivnce_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getNewProivnceName() {
        return newProivnceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_proivnce_name
     *
     * @param newProivnceName the value for edu_jobtransfer_history.new_proivnce_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewProivnceName(String newProivnceName) {
        this.newProivnceName = newProivnceName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_province_id
     *
     * @return the value of edu_jobtransfer_history.new_province_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getNewProvinceId() {
        return newProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_province_id
     *
     * @param newProvinceId the value for edu_jobtransfer_history.new_province_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewProvinceId(Integer newProvinceId) {
        this.newProvinceId = newProvinceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_city_id
     *
     * @return the value of edu_jobtransfer_history.new_city_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getNewCityId() {
        return newCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_city_id
     *
     * @param newCityId the value for edu_jobtransfer_history.new_city_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewCityId(Integer newCityId) {
        this.newCityId = newCityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_city_name
     *
     * @return the value of edu_jobtransfer_history.new_city_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getNewCityName() {
        return newCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_city_name
     *
     * @param newCityName the value for edu_jobtransfer_history.new_city_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewCityName(String newCityName) {
        this.newCityName = newCityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_district_id
     *
     * @return the value of edu_jobtransfer_history.new_district_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getNewDistrictId() {
        return newDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_district_id
     *
     * @param newDistrictId the value for edu_jobtransfer_history.new_district_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewDistrictId(Integer newDistrictId) {
        this.newDistrictId = newDistrictId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_district_name
     *
     * @return the value of edu_jobtransfer_history.new_district_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getNewDistrictName() {
        return newDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_district_name
     *
     * @param newDistrictName the value for edu_jobtransfer_history.new_district_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewDistrictName(String newDistrictName) {
        this.newDistrictName = newDistrictName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_school_name
     *
     * @return the value of edu_jobtransfer_history.new_school_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getNewSchoolName() {
        return newSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_school_name
     *
     * @param newSchoolName the value for edu_jobtransfer_history.new_school_name
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewSchoolName(String newSchoolName) {
        this.newSchoolName = newSchoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_school_id
     *
     * @return the value of edu_jobtransfer_history.new_school_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getNewSchoolId() {
        return newSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_school_id
     *
     * @param newSchoolId the value for edu_jobtransfer_history.new_school_id
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewSchoolId(Integer newSchoolId) {
        this.newSchoolId = newSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.create_by
     *
     * @return the value of edu_jobtransfer_history.create_by
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.create_by
     *
     * @param createBy the value for edu_jobtransfer_history.create_by
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.create_date
     *
     * @return the value of edu_jobtransfer_history.create_date
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.create_date
     *
     * @param createDate the value for edu_jobtransfer_history.create_date
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.old_version
     *
     * @return the value of edu_jobtransfer_history.old_version
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getOldVersion() {
        return oldVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.old_version
     *
     * @param oldVersion the value for edu_jobtransfer_history.old_version
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setOldVersion(Integer oldVersion) {
        this.oldVersion = oldVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column edu_jobtransfer_history.new_version
     *
     * @return the value of edu_jobtransfer_history.new_version
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public Integer getNewVersion() {
        return newVersion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column edu_jobtransfer_history.new_version
     *
     * @param newVersion the value for edu_jobtransfer_history.new_version
     *
     * @abatorgenerated Mon Apr 07 11:54:44 CST 2014
     */
    public void setNewVersion(Integer newVersion) {
        this.newVersion = newVersion;
    }
}