package project.teacher.teachermanage.pojo;

import java.util.Date;
import org.apache.log4j.Logger;


public class EduTeacherEducation  implements Cloneable {
	private static final Logger log = Logger.getLogger(EduTeacherEducation.class);
	public Object clone() { 
		EduTeacherEducation o = null;
		try {  
	         o = (EduTeacherEducation) super.clone();  
	    } catch (CloneNotSupportedException e) {  
	    	log.error("对象拷贝出错", e);  
	    }  
		return o;
	}

	//学历
	private Integer educationExperienceType;
	
	// 学位
	private Integer educationDegreeType;
	
	public Integer getEducationExperienceType() {
		return educationExperienceType;
	}

	public void setEducationExperienceType(Integer educationExperienceType) {
		this.educationExperienceType = educationExperienceType;
	}

	public Integer getEducationDegreeType() {
		return educationDegreeType;
	}

	public void setEducationDegreeType(Integer educationDegreeType) {
		this.educationDegreeType = educationDegreeType;
	}

	private Integer status;
	
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.teacher_id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer teacherId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_experience
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationExperience;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_degree
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationDegree;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_graduation_time
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationGraduationTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_graduation_school
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationGraduationSchool;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_graduation_profession
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationGraduationProfession;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.sort
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_update_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationUpdateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_create_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private String educationCreateBy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_create_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Date educationCreateDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.education_update_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Date educationUpdateDate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column edu_teacher_education.version
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	private Integer version;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.id
	 * @return  the value of edu_teacher_education.id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.id
	 * @param id  the value for edu_teacher_education.id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.teacher_id
	 * @return  the value of edu_teacher_education.teacher_id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getTeacherId() {
		return teacherId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.teacher_id
	 * @param teacherId  the value for edu_teacher_education.teacher_id
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_experience
	 * @return  the value of edu_teacher_education.education_experience
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationExperience() {
		return educationExperience;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_experience
	 * @param educationExperience  the value for edu_teacher_education.education_experience
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationExperience(String educationExperience) {
		this.educationExperience = educationExperience;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_degree
	 * @return  the value of edu_teacher_education.education_degree
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationDegree() {
		return educationDegree;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_degree
	 * @param educationDegree  the value for edu_teacher_education.education_degree
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationDegree(String educationDegree) {
		this.educationDegree = educationDegree;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_graduation_time
	 * @return  the value of edu_teacher_education.education_graduation_time
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationGraduationTime() {
		return educationGraduationTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_graduation_time
	 * @param educationGraduationTime  the value for edu_teacher_education.education_graduation_time
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationGraduationTime(String educationGraduationTime) {
		this.educationGraduationTime = educationGraduationTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_graduation_school
	 * @return  the value of edu_teacher_education.education_graduation_school
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationGraduationSchool() {
		return educationGraduationSchool;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_graduation_school
	 * @param educationGraduationSchool  the value for edu_teacher_education.education_graduation_school
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationGraduationSchool(String educationGraduationSchool) {
		this.educationGraduationSchool = educationGraduationSchool;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_graduation_profession
	 * @return  the value of edu_teacher_education.education_graduation_profession
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationGraduationProfession() {
		return educationGraduationProfession;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_graduation_profession
	 * @param educationGraduationProfession  the value for edu_teacher_education.education_graduation_profession
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationGraduationProfession(
			String educationGraduationProfession) {
		this.educationGraduationProfession = educationGraduationProfession;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.sort
	 * @return  the value of edu_teacher_education.sort
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.sort
	 * @param sort  the value for edu_teacher_education.sort
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_update_by
	 * @return  the value of edu_teacher_education.education_update_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationUpdateBy() {
		return educationUpdateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_update_by
	 * @param educationUpdateBy  the value for edu_teacher_education.education_update_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationUpdateBy(String educationUpdateBy) {
		this.educationUpdateBy = educationUpdateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_create_by
	 * @return  the value of edu_teacher_education.education_create_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public String getEducationCreateBy() {
		return educationCreateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_create_by
	 * @param educationCreateBy  the value for edu_teacher_education.education_create_by
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationCreateBy(String educationCreateBy) {
		this.educationCreateBy = educationCreateBy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_create_date
	 * @return  the value of edu_teacher_education.education_create_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Date getEducationCreateDate() {
		return educationCreateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_create_date
	 * @param educationCreateDate  the value for edu_teacher_education.education_create_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationCreateDate(Date educationCreateDate) {
		this.educationCreateDate = educationCreateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.education_update_date
	 * @return  the value of edu_teacher_education.education_update_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Date getEducationUpdateDate() {
		return educationUpdateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.education_update_date
	 * @param educationUpdateDate  the value for edu_teacher_education.education_update_date
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setEducationUpdateDate(Date educationUpdateDate) {
		this.educationUpdateDate = educationUpdateDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column edu_teacher_education.version
	 * @return  the value of edu_teacher_education.version
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column edu_teacher_education.version
	 * @param version  the value for edu_teacher_education.version
	 * @abatorgenerated  Thu Mar 27 21:28:59 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}